title: "Tutorial: Planning for Storytelling"
description: "An ICAPS 2024 Tutorial on Planning for Storytelling"
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://planning4storytelling.github.io/icaps-tutorial-2024" # the base hostname & protocol for your site
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
